[package]
name = "commix"
version = "0.5.2"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.15"
midir = "0.10"
cpal = "0.15"
hound = "3"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
